=== MaxiCode/GreenDev/code/profilingTools/ExtensibleJavaProfiler/ejp-r2_2b1-unix-common/etc/settings/settings.dtd
<!--
  Application's settings definition file.

  Author: Sebastien Vauclair
  Version: $Revision: 1.3 $ $Date: 2003/06/11 17:13:30 $
  -->

<!ELEMENT settings
  (default-filters*, filter-customization*, run-program-dialog?, filter-customization*)>

<!ELEMENT default-filters EMPTY>
<!ATTLIST default-filters
  full-names CDATA #REQUIRED
  >
  
<!ELEMENT run-program-dialog EMPTY>
<!ATTLIST run-program-dialog
  source-paths CDATA #IMPLIED
  command-template CDATA #IMPLIED
  >

<!ELEMENT filter-customization (parameter+)>
<!ATTLIST filter-customization
  full-name ID #REQUIRED
  >

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
  name CDATA #REQUIRED
  value CDATA #REQUIRED
  >

=== MaxiCode/GreenDev/code/profilingTools/ExtensibleJavaProfiler/ejp-r2_2b1-unix-common/src/presenter-src/etc/settings/default.xml
<!--
  Application's default settings.

  Author: Sebastien Vauclair
  Version: $Revision: 1.4 $ $Date: 2003/08/06 13:08:58 $
  -->

<!-- This file is automatically generated. -->
<!-- Any additions might be overwritten without notice. -->

<!DOCTYPE settings SYSTEM "settings.dtd">

<settings
  >

  <default-filters
    full-names="Common.Highlight-hot-spots Common.Display-total-time-percent Common.Display-total-time"
    />

  <filter-customization
    full-name="Common.Highlight-hot-spots"
    >

    <parameter
      name="color-distribution"
      value="-16777216;-14942208;-13107200;-11206656;-9371648;-7536640;-5636096;-3801088;-1966080;-65536"
      />

  </filter-customization>

  <filter-customization
    full-name="Common.Display-total-time-percent"
    >

    <parameter
      name="relative-to-parent"
      value="false"
      />

  </filter-customization>

  <filter-customization
    full-name="Common.Display-total-time"
    >

    <parameter
      name="use-best-unit"
      value="true"
      />

  </filter-customization>

  <filter-customization
    full-name="Common.Sort-by-text"
    >

    <parameter
      name="descending-sort-order"
      value="false"
      />

  </filter-customization>

  <filter-customization
    full-name="Common.Sort-by-total-time"
    >

    <parameter
      name="descending-sort-order"
      value="true"
      />

  </filter-customization>

  <filter-customization
    full-name="Common.Remove-packages"
    >

    <parameter
      name="packages"
      value="org.jboss"
      />

  </filter-customization>

  <run-program-dialog
    source-paths="c:\prog\jdk\src;c:\java"
    command-template="emacs +%l %p%f"
    />

</settings>
