=== MaxiCode/GreenDev/code/profilingTools/ExtensibleJavaProfiler/ejp-r2_2b1-unix-common/src/presenter-src/etc/filters/filters.dtd
<!--
  Filters description definition file.

  Author: Sebastien Vauclair
  Version: $Revision: 1.2 $ $Date: 2002/03/27 16:37:46 $
  -->

<!ELEMENT filters (directory | filter)+>

<!ELEMENT directory (directory | filter)+>
<!ATTLIST directory
  name NMTOKEN #REQUIRED
  >

<!ELEMENT filter EMPTY>
<!ATTLIST filter
  name NMTOKEN #REQUIRED
  class-name CDATA #REQUIRED
  description CDATA #IMPLIED
  version CDATA #IMPLIED
  author CDATA #IMPLIED
  requires CDATA #IMPLIED
  must-follow CDATA #IMPLIED
  must-precede CDATA #IMPLIED
  >

=== MaxiCode/GreenDev/code/profilingTools/ExtensibleJavaProfiler/ejp-r2_2b1-unix-common/etc/filters/default.xml
<!DOCTYPE filters SYSTEM "filters.dtd">

<!--
  Description file for default filters.

  Author: Sebastien Vauclair
  Version: $Revision: 1.4 $ $Date: 2004/01/16 15:21:53 $
  -->

<!--
  REPLACE Filters that replace children nodes
  RENDER  Filters that render nodes
  ORDER   Filters that order children nodes
  REMOVE  Filters that remove children nodes
  -->

<filters>

  <directory
    name="Common"
    >

    <!-- REPLACE -->

    <filter
      name="Accumulate-methods"
      class-name="ejp.presenter.api.filters.AccumulateMethods"
      description="Regroups identical method calls"
      />

    <!-- RENDER -->

    <filter
      name="Display-total-time"
      class-name="ejp.presenter.api.filters.DisplayTotalTime"
      description="Displays nodes' total time"
      must-follow="Accumulate-methods"
      />

    <filter
      name="Display-total-time-percent"
      class-name="ejp.presenter.api.filters.DisplayTotalTimePercent"
      description="Computes and displays nodes' percent of time"
      must-follow="Accumulate-methods"
      />

    <!-- requires Display-total-time-percent which actually computes ratio -->
    <filter
      name="Highlight-hot-spots"
      class-name="ejp.presenter.api.filters.HighlightHotSpots"
      description="Highlights nodes depending on their associated time percent"
      requires="Display-total-time-percent"
      must-follow="Accumulate-methods
                   Display-total-time-percent"
      />

    <!-- ORDER -->

    <filter
      name="Sort-by-text"
      class-name="ejp.presenter.api.filters.SortByText"
      description="Sorts nodes by method names"
      must-follow="Accumulate-methods"
      />

    <filter
      name="Sort-by-total-time"
      class-name="ejp.presenter.api.filters.SortByTotalTime"
      description="Sorts nodes by total time"
      must-follow="Accumulate-methods"
      />

    <!-- REMOVE -->

    <!-- must precede any filter that depends on parent -->
    <filter
      name="Remove-packages"
      class-name="ejp.presenter.api.filters.RemovePackages"
      description="Removes any node from classes in specified packages"
      must-precede="Common.Accumulate-methods

                    Common.Sort-by-total-time
                    Common.Sort-by-text

                    Common.Display-total-time-percent"
      />
      
    <filter
      name="Remove-non-significant"
      class-name="ejp.presenter.api.filters.RemoveNonSignificant"
      description="Removes any node which time is lower than some threshold"
      must-precede="Common.Accumulate-methods

                    Common.Sort-by-total-time
                    Common.Sort-by-text

                    Common.Display-total-time-percent"
      />      

  </directory>

  <directory
    name="Funnel"
    >

    <!-- REPLACE -->

    <!-- constraints are placed on others because filter is alone in categ. -->
    <filter
      name="Hide-tail-call-eliminations"
      class-name="ejp.presenter.api.filters.HideFunnelTCEliminations"
      description="Hides tail call eliminations (callContinuation() methods)"
      requires="Remove-duplicate-in-TCE"
      must-precede="Common.Sort-by-text
                    Common.Sort-by-total-time

                    Common.Display-total-time
                    Common.Display-total-time-percent
                    Common.Highlight-hot-spots

                    Common.Accumulate-methods"
      must-follow="Common.Remove-packages"
      />

    <!-- REMOVE -->

    <!-- must precede any filter that depends on parent -->
    <filter
      name="Remove-dispatches"
      class-name="ejp.presenter.api.filters.RemoveFunnelDispatches"
      description="Removes any node representing a dispatch method"
      must-precede="Common.Accumulate-methods
                    Hide-tail-call-eliminations

                    Common.Sort-by-total-time
                    Common.Sort-by-text

                    Common.Display-total-time-percent"
      />

    <!-- must precede any filter that depends on parent -->
    <filter
      name="Remove-Funnel-runtime"
      class-name="ejp.presenter.api.filters.RemoveFunnelRuntime"
      description="Removes any node from a class in funnel.runtime.* package"
      must-precede="Common.Accumulate-methods
                    Hide-tail-call-eliminations

                    Common.Sort-by-total-time
                    Common.Sort-by-text

                    Common.Display-total-time-percent"
      />

    <!-- must precede any filter that depends on parent -->
    <filter
      name="Remove-Java-runtime"
      class-name="ejp.presenter.api.filters.RemoveJavaRuntime"
      description="Removes any node from a class in java.* or sun.* packages"
      must-precede="Common.Accumulate-methods
                    Hide-tail-call-eliminations

                    Common.Sort-by-total-time
                    Common.Sort-by-text

                    Common.Display-total-time-percent"
      />

    <!-- must follow R-d and R-F-r to coorectly detect duplicate -->
    <filter
      name="Remove-duplicate-in-TCE"
      class-name="ejp.presenter.api.filters.RemoveDuplicateInTCE"
      description="Accumulates duplicate method call created as a result of hiding tail call elimination"
      must-precede="Common.Accumulate-methods
                    Hide-tail-call-eliminations

                    Common.Sort-by-total-time
                    Common.Sort-by-text

                    Common.Display-total-time-percent"
      must-follow="Remove-dispatches
                   Remove-Funnel-runtime"
      />

    <!-- RENDER -->

    <!-- must follow Unmangle-names to prevail on it -->
    <filter
      name="Rename-concepts"
      class-name="ejp.presenter.api.filters.RenameFunnelConcepts"
      description="Renames Funnel selfq() and lazy() methods to more explicit names"
      must-follow="Common.Accumulate-methods
                   Hide-tail-call-eliminations

                   Unmangle-names"
      />

    <filter
      name="Unmangle-names"
      class-name="ejp.presenter.api.filters.UnmangleFunnelNames"
      description="Removes compiler-added decorations to Funnel functions names"
      must-follow="Common.Accumulate-methods
                   Hide-tail-call-eliminations"
      />

  </directory>

</filters>
